### ISSUE TITLE
Add "myGame" attribute to game status

### ISSUE THREAD

**Issue by dasmo90** [dasmo90/texting#5]
In frontend we need to know, if the current game is owned by the user or not. It is needed in the game initialization phase, where only the game owner can start or shut the game.

Add an attribute "myGame" of type "boolean" to the GameStatus class. The attribute should be available in any game phase.

**Comment by dasmo90** [comment]
The attribute should be set to "true" if and only if the owner requests the game status.

**Comment by Shatah** [comment]
The attribute "myGame" is now present and awailable in any game phase. However, once the game has been started, there is no game owner anymore, so myGame will always be false from then on.

**Comment by dasmo90** [comment]
This matches perfectly to the frontend understanding of the game phases.
